import Header from '@/components/layout/Header';
import ToasterProvider from '@/components/ui/ToasterProvider';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.className} text-black bg-tertiary sm:h-screen max-w-[85rem] my-0 mx-auto grid grid-cols-1 sm:grid-cols-[3fr_2fr] grid-rows-[60px_70px_1fr] gap-3 sm:gap-x-8 pt-0 px-8 pb-4`}
      >
        <Header />
        {children}
        <ToasterProvider />
      </body>
    </html>
  );
}
