import Header from '@/components/layout/Header';
import ToasterProvider from '@/components/ui/ToasterProvider';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// color: #444;
// background-color: #f3f3f3;
// height: 100vh;
// max-width: 85rem;
// margin: 0 auto;
// display: grid;
// grid-template-columns: 3fr 2fr;
// grid-template-rows: 60px 70px 1fr;
// column-gap: 2rem;
// padding: 0 2rem 1rem;

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.className} text-black bg-tertiary sm:h-screen max-w-[85rem] my-0 mx-auto grid grid-cols-1 sm:grid-cols-[3fr_2fr] grid-rows-[60px_70px_1fr] gap-3 sm:gap-x-8 pt-0 px-8 pb-4`}
      >
        <Header />
        {children}
        <ToasterProvider />
      </body>
    </html>
  );
}
